name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check for ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          quiet: false
          ticketLink: 'https://mack.atlassian.net/browse/AB-%ticketNumber%'
          ticketPrefix: 'AB-'
          titleRegex: '^AB-(?<ticketNumber>\d+)'
          branchRegex: '^AB-(?<ticketNumber>\d+)'
          bodyRegex: 'AB-(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(mack.atlassian.net)(\/browse)\/(AB\-)(?<ticketNumber>\d+)'
